import type { SymbolDefinition } from "./types";

const majors = [
  ["EUR/USD","EUR","USD","Euro / US Dollar",5],["GBP/USD","GBP","USD","British Pound / US Dollar",5],["USD/JPY","USD","JPY","US Dollar / Japanese Yen",3],["USD/CHF","USD","CHF","US Dollar / Swiss Franc",5],["AUD/USD","AUD","USD","Australian Dollar / US Dollar",5],["USD/CAD","USD","CAD","US Dollar / Canadian Dollar",5],["NZD/USD","NZD","USD","New Zealand Dollar / US Dollar",5],
] as const;
const minors = [
  ["EUR/GBP","EUR","GBP","Euro / British Pound"],["EUR/JPY","EUR","JPY","Euro / Japanese Yen"],["EUR/CHF","EUR","CHF","Euro / Swiss Franc"],["EUR/AUD","EUR","AUD","Euro / Australian Dollar"],["EUR/CAD","EUR","CAD","Euro / Canadian Dollar"],["EUR/NZD","EUR","NZD","Euro / New Zealand Dollar"],["GBP/JPY","GBP","JPY","British Pound / Japanese Yen"],["GBP/CHF","GBP","CHF","British Pound / Swiss Franc"],["GBP/AUD","GBP","AUD","British Pound / Australian Dollar"],["GBP/CAD","GBP","CAD","British Pound / Canadian Dollar"],["GBP/NZD","GBP","NZD","British Pound / New Zealand Dollar"],["AUD/JPY","AUD","JPY","Australian Dollar / Japanese Yen"],["AUD/NZD","AUD","NZD","Australian Dollar / New Zealand Dollar"],["AUD/CAD","AUD","CAD","Australian Dollar / Canadian Dollar"],["AUD/CHF","AUD","CHF","Australian Dollar / Swiss Franc"],["NZD/JPY","NZD","JPY","New Zealand Dollar / Japanese Yen"],["NZD/CAD","NZD","CAD","New Zealand Dollar / Canadian Dollar"],["NZD/CHF","NZD","CHF","New Zealand Dollar / Swiss Franc"],["CAD/JPY","CAD","JPY","Canadian Dollar / Japanese Yen"],["CAD/CHF","CAD","CHF","Canadian Dollar / Swiss Franc"],["CHF/JPY","CHF","JPY","Swiss Franc / Japanese Yen"],
] as const;
const exotics = [
  ["USD/TRY","USD","TRY","US Dollar / Turkish Lira"],["USD/ZAR","USD","ZAR","US Dollar / South African Rand"],["USD/MXN","USD","MXN","US Dollar / Mexican Peso"],["USD/SGD","USD","SGD","US Dollar / Singapore Dollar"],["USD/HKD","USD","HKD","US Dollar / Hong Kong Dollar"],["USD/NOK","USD","NOK","US Dollar / Norwegian Krone"],["USD/SEK","USD","SEK","US Dollar / Swedish Krona"],["USD/DKK","USD","DKK","US Dollar / Danish Krone"],["USD/PLN","USD","PLN","US Dollar / Polish Zloty"],["USD/HUF","USD","HUF","US Dollar / Hungarian Forint"],["USD/CNH","USD","CNH","US Dollar / Offshore Yuan"],["USD/CZK","USD","CZK","US Dollar / Czech Koruna"],["USD/RON","USD","RON","US Dollar / Romanian Leu"],["USD/ILS","USD","ILS","US Dollar / Israeli Shekel"],["USD/THB","USD","THB","US Dollar / Thai Baht"],["USD/MYR","USD","MYR","US Dollar / Malaysian Ringgit"],["USD/INR","USD","INR","US Dollar / Indian Rupee"],["USD/BRL","USD","BRL","US Dollar / Brazilian Real"],["USD/CLP","USD","CLP","US Dollar / Chilean Peso"],["USD/COP","USD","COP","US Dollar / Colombian Peso"],["USD/PEN","USD","PEN","US Dollar / Peruvian Sol"],["EUR/TRY","EUR","TRY","Euro / Turkish Lira"],["EUR/PLN","EUR","PLN","Euro / Polish Zloty"],["EUR/NOK","EUR","NOK","Euro / Norwegian Krone"],["EUR/SEK","EUR","SEK","Euro / Swedish Krona"],["EUR/DKK","EUR","DKK","Euro / Danish Krone"],["EUR/HUF","EUR","HUF","Euro / Hungarian Forint"],["EUR/CZK","EUR","CZK","Euro / Czech Koruna"],["EUR/RON","EUR","RON","Euro / Romanian Leu"],["EUR/ZAR","EUR","ZAR","Euro / South African Rand"],["GBP/TRY","GBP","TRY","British Pound / Turkish Lira"],["GBP/ZAR","GBP","ZAR","British Pound / South African Rand"],["GBP/NOK","GBP","NOK","British Pound / Norwegian Krone"],["GBP/SEK","GBP","SEK","British Pound / Swedish Krona"],["GBP/PLN","GBP","PLN","British Pound / Polish Zloty"],["AUD/SGD","AUD","SGD","Australian Dollar / Singapore Dollar"],["AUD/TRY","AUD","TRY","Australian Dollar / Turkish Lira"],["NZD/SGD","NZD","SGD","New Zealand Dollar / Singapore Dollar"],["CAD/SGD","CAD","SGD","Canadian Dollar / Singapore Dollar"],["CHF/SGD","CHF","SGD","Swiss Franc / Singapore Dollar"],
] as const;

function make(rows: readonly (readonly [string,string,string,string,number?])[], category: SymbolDefinition["category"]): SymbolDefinition[] { return rows.map(([symbol,base,quote,name,digits]) => ({ symbol,base,quote,name,digits: digits ?? (quote === "JPY" ? 3 : 5),category })); }
export const forexSymbols = [...make(majors,"majors"),...make(minors,"minors"),...make(exotics,"exotics")];
export const defaultWatchlist = ["EUR/USD","GBP/USD","USD/JPY","USD/CHF","AUD/USD","USD/CAD","NZD/USD","EUR/JPY","GBP/JPY","EUR/GBP"];
