"""Transport and cache ports for infrastructure adapters."""
from typing import Protocol
from cfip.domain.event_contracts import EventEnvelope

class EventPublisher(Protocol):
    async def publish(self, topic: str, event: EventEnvelope) -> None: ...

class EventSubscriber(Protocol):
    async def subscribe(self, topic: str) -> object: ...

class CachePort(Protocol):
    async def get(self, key: str) -> bytes | None: ...
    async def set(self, key: str, value: bytes, ttl_seconds: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
