"""Application ports for persistent terminal workspaces."""
from typing import Protocol
from cfip.domain.workspace_contracts import Workspace

class WorkspaceRepository(Protocol):
    async def get(self, user_id: str, workspace_id: str) -> Workspace | None: ...
    async def list(self, user_id: str) -> tuple[Workspace, ...]: ...
    async def save(self, workspace: Workspace) -> Workspace: ...
