"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AreaSeries, BarSeries, BaselineSeries, CandlestickSeries, ColorType, CrosshairMode, HistogramSeries, LineSeries, createChart, type IChartApi, type ISeriesApi, type SeriesType, type UTCTimestamp } from "lightweight-charts";
import type { MarketObservation } from "@/lib/api";

type ChartType = "candles" | "bars" | "line" | "area" | "baseline";
type Timeframe = "1m" | "5m" | "15m" | "1H" | "4H" | "1D";
type Indicator = "sma20" | "ema20" | "ema50" | "wma20" | "bb20" | "vwap";
type Oscillator = "rsi14" | "macd" | "stoch14" | "atr14" | "cci20" | "adx14" | "obv";
type DrawingTool = "cursor" | "horizontal" | "vertical" | "trendline" | "ray" | "rectangle" | "fib";
type Overlay = "fvg" | "ob" | "structure" | "liquidity" | "sessions";
interface Candle { time: UTCTimestamp; open: number; high: number; low: number; close: number; volume: number }
interface Zone { start: UTCTimestamp; end: UTCTimestamp; top: number; bottom: number; kind: "bullish" | "bearish" }
interface Point { time: UTCTimestamp; price: number }
interface Drawing { tool: Exclude<DrawingTool, "cursor">; a: Point; b: Point }

const TF: Record<Timeframe, number> = { "1m": 60, "5m": 300, "15m": 900, "1H": 3600, "4H": 14400, "1D": 86400 };
const TIMEFRAMES: Timeframe[] = ["1m", "5m", "15m", "1H", "4H", "1D"];
const INDICATORS: { id: Indicator; label: string }[] = [
  { id: "sma20", label: "SMA 20" }, { id: "ema20", label: "EMA 20" }, { id: "ema50", label: "EMA 50" },
  { id: "wma20", label: "WMA 20" }, { id: "bb20", label: "Bollinger 20" }, { id: "vwap", label: "VWAP" },
];
const OSCILLATORS: { id: Oscillator; label: string }[] = [
  { id: "rsi14", label: "RSI 14" }, { id: "macd", label: "MACD 12/26/9" }, { id: "stoch14", label: "Stochastic 14" },
  { id: "atr14", label: "ATR 14" }, { id: "cci20", label: "CCI 20" }, { id: "adx14", label: "ADX 14" }, { id: "obv", label: "OBV" },
];

function aggregate(observations: MarketObservation[], timeframe: Timeframe): Candle[] {
  const seconds = TF[timeframe];
  const sorted = observations.map((o) => ({ o, t: Math.floor(new Date(o.observed_at).getTime() / 1000) })).filter(({ o, t }) => Number.isFinite(t) && (o.last ?? o.bid ?? o.ask) !== null).sort((a, b) => a.t - b.t);
  const buckets = new Map<number, Candle>();
  for (const { o, t } of sorted) {
    const raw = o.last ?? o.bid ?? o.ask; if (raw === null) continue;
    const price = Number(raw); if (!Number.isFinite(price)) continue;
    const key = Math.floor(t / seconds) * seconds; const volume = Number(o.volume ?? 0); const v = Number.isFinite(volume) && volume >= 0 ? volume : 0;
    const current = buckets.get(key);
    if (!current) buckets.set(key, { time: key as UTCTimestamp, open: price, high: price, low: price, close: price, volume: v });
    else { current.high = Math.max(current.high, price); current.low = Math.min(current.low, price); current.close = price; current.volume += v; }
  }
  return [...buckets.values()];
}
function sma(c: Candle[], p: number) { return c.flatMap((x, i) => i + 1 < p ? [] : [{ time: x.time, value: c.slice(i + 1 - p, i + 1).reduce((s, q) => s + q.close, 0) / p }]); }
function ema(c: Candle[], p: number) { if (c.length < p) return [] as { time: UTCTimestamp; value: number }[]; const out: { time: UTCTimestamp; value: number }[] = []; let value = c.slice(0, p).reduce((s, x) => s + x.close, 0) / p; const k = 2 / (p + 1); out.push({ time: c[p - 1].time, value }); for (let i = p; i < c.length; i += 1) { value += (c[i].close - value) * k; out.push({ time: c[i].time, value }); } return out; }
function wma(c: Candle[], p: number) { const weight = (p * (p + 1)) / 2; return c.flatMap((x, i) => i + 1 < p ? [] : [{ time: x.time, value: c.slice(i + 1 - p, i + 1).reduce((s, q, j) => s + q.close * (j + 1), 0) / weight }]); }
function bb(c: Candle[], p = 20, mult = 2) { return c.flatMap((x, i) => { if (i + 1 < p) return []; const v = c.slice(i + 1 - p, i + 1).map((q) => q.close); const m = v.reduce((s, q) => s + q, 0) / p; const d = Math.sqrt(v.reduce((s, q) => s + (q - m) ** 2, 0) / p) * mult; return [{ time: x.time, upper: m + d, middle: m, lower: m - d }]; }); }
function vwap(c: Candle[]) { let pv = 0; let vol = 0; return c.map((x) => { const v = x.volume > 0 ? x.volume : 1; pv += ((x.high + x.low + x.close) / 3) * v; vol += v; return { time: x.time, value: pv / vol }; }); }
function rsi(c: Candle[], p = 14) { if (c.length <= p) return [] as { time: UTCTimestamp; value: number }[]; let gain = 0; let loss = 0; for (let i = 1; i <= p; i += 1) { const d = c[i].close - c[i - 1].close; gain += Math.max(d, 0); loss += Math.max(-d, 0); } let ag = gain / p; let al = loss / p; const out = [{ time: c[p].time, value: al === 0 ? 100 : 100 - 100 / (1 + ag / al) }]; for (let i = p + 1; i < c.length; i += 1) { const d = c[i].close - c[i - 1].close; ag = (ag * (p - 1) + Math.max(d, 0)) / p; al = (al * (p - 1) + Math.max(-d, 0)) / p; out.push({ time: c[i].time, value: al === 0 ? 100 : 100 - 100 / (1 + ag / al) }); } return out; }
function trueRange(c: Candle[]) { return c.map((x, i) => i === 0 ? x.high - x.low : Math.max(x.high - x.low, Math.abs(x.high - c[i - 1].close), Math.abs(x.low - c[i - 1].close))); }
function atr(c: Candle[], p = 14) { const tr = trueRange(c); return tr.map((_, i) => i + 1 < p ? null : { time: c[i].time, value: tr.slice(i + 1 - p, i + 1).reduce((s, x) => s + x, 0) / p }).filter((x): x is { time: UTCTimestamp; value: number } => x !== null); }
function macd(c: Candle[]) { const fast = ema(c, 12); const slow = ema(c, 26); const map = new Map(slow.map((x) => [Number(x.time), x.value])); const line = fast.flatMap((x) => { const s = map.get(Number(x.time)); return s === undefined ? [] : [{ time: x.time, value: x.value - s }]; }); const signal = ema(line.map((x) => ({ time: x.time, open: x.value, high: x.value, low: x.value, close: x.value, volume: 0 })), 9); const sm = new Map(signal.map((x) => [Number(x.time), x.value])); return { line, signal, hist: line.flatMap((x) => { const s = sm.get(Number(x.time)); return s === undefined ? [] : [{ time: x.time, value: x.value - s }]; }) }; }
function stochastic(c: Candle[], p = 14) { return c.flatMap((x, i) => { if (i + 1 < p) return []; const w = c.slice(i + 1 - p, i + 1); const hi = Math.max(...w.map((q) => q.high)); const lo = Math.min(...w.map((q) => q.low)); return [{ time: x.time, value: hi === lo ? 50 : ((x.close - lo) / (hi - lo)) * 100 }]; }); }
function cci(c: Candle[], p = 20) { return c.flatMap((x, i) => { if (i + 1 < p) return []; const w = c.slice(i + 1 - p, i + 1).map((q) => (q.high + q.low + q.close) / 3); const m = w.reduce((s, q) => s + q, 0) / p; const md = w.reduce((s, q) => s + Math.abs(q - m), 0) / p; return [{ time: x.time, value: md === 0 ? 0 : (((x.high + x.low + x.close) / 3 - m) / (0.015 * md)) }]; }); }
function adx(c: Candle[], p = 14) { const tr = trueRange(c); const plus = c.map((x, i) => i === 0 ? 0 : Math.max(x.high - c[i - 1].high, 0)); const minus = c.map((x, i) => i === 0 ? 0 : Math.max(c[i - 1].low - x.low, 0)); return c.flatMap((x, i) => { if (i + 1 < p) return []; const t = tr.slice(i + 1 - p, i + 1).reduce((s, q) => s + q, 0); if (t === 0) return []; const pdi = (plus.slice(i + 1 - p, i + 1).reduce((s, q) => s + q, 0) / t) * 100; const mdi = (minus.slice(i + 1 - p, i + 1).reduce((s, q) => s + q, 0) / t) * 100; return [{ time: x.time, value: pdi + mdi === 0 ? 0 : (Math.abs(pdi - mdi) / (pdi + mdi)) * 100 }]; }); }
function obv(c: Candle[]) { let value = 0; return c.map((x, i) => { if (i > 0) value += x.close > c[i - 1].close ? x.volume : x.close < c[i - 1].close ? -x.volume : 0; return { time: x.time, value }; }); }
function zones(c: Candle[], kind: "fvg" | "ob"): Zone[] { const out: Zone[] = []; const end = c.at(-1)?.time; if (end === undefined) return out; if (kind === "fvg") { for (let i = 2; i < c.length; i += 1) { const a = c[i - 2]; const b = c[i]; if (a.high < b.low) out.push({ start: c[i - 1].time, end, bottom: a.high, top: b.low, kind: "bullish" }); else if (a.low > b.high) out.push({ start: c[i - 1].time, end, bottom: b.high, top: a.low, kind: "bearish" }); } } else { for (let i = 1; i < c.length; i += 1) { const a = c[i - 1]; const b = c[i]; const range = Math.max(b.high - b.low, Number.EPSILON); if (Math.abs(b.close - b.open) / range < 0.6) continue; if (b.close > b.open && a.close < a.open) out.push({ start: a.time, end, top: a.high, bottom: a.low, kind: "bullish" }); if (b.close < b.open && a.close > a.open) out.push({ start: a.time, end, top: a.high, bottom: a.low, kind: "bearish" }); } } return out.slice(-12); }
function pivots(c: Candle[]) { const out: { time: UTCTimestamp; price: number; label: string }[] = []; for (let i = 2; i < c.length - 2; i += 1) { if (c[i].high > c[i - 1].high && c[i].high >= c[i + 1].high) out.push({ time: c[i].time, price: c[i].high, label: "SH" }); if (c[i].low < c[i - 1].low && c[i].low <= c[i + 1].low) out.push({ time: c[i].time, price: c[i].low, label: "SL" }); } return out.slice(-20); }

const chartOptions = {
  autoSize: true,
  layout: { background: { type: ColorType.Solid, color: "#080b10" }, textColor: "#a7b0be", attributionLogo: true, panes: { separatorColor: "#1b2430", separatorHoverColor: "#334154", enableResize: true } },
  grid: { vertLines: { color: "#121923" }, horzLines: { color: "#121923" } },
  rightPriceScale: { borderColor: "#25303d", autoScale: true, alignLabels: true }, leftPriceScale: { visible: false, borderColor: "#25303d", autoScale: true, alignLabels: true }, defaultVisiblePriceScaleId: "right",
  timeScale: { borderColor: "#25303d", timeVisible: true, secondsVisible: false, rightOffset: 8, barSpacing: 7, minBarSpacing: 2, maxBarSpacing: 20 },
  crosshair: { mode: CrosshairMode.Normal, vertLine: { color: "#65748a", width: 1, style: 3, labelBackgroundColor: "#2b394c" }, horzLine: { color: "#65748a", width: 1, style: 3, labelBackgroundColor: "#2b394c" } },
  handleScroll: { mouseWheel: true, pressedMouseMove: true, horzTouchDrag: true, vertTouchDrag: true }, handleScale: { mouseWheel: true, pinch: true, axisPressedMouseMove: true, axisDoubleClickReset: true }, kineticScroll: { mouse: true, touch: true }, hoveredSeriesOnTop: true,
} as const;

interface Props { observations: MarketObservation[]; symbol?: string; }

export function CfipChartTerminal({ observations, symbol = "EUR/USD" }: Props) {
  const hostRef = useRef<HTMLDivElement>(null); const chartRef = useRef<IChartApi | null>(null); const mainRef = useRef<ISeriesApi<SeriesType> | null>(null); const overlayRef = useRef<HTMLDivElement>(null);
  const [timeframe, setTimeframe] = useState<Timeframe>("15m"); const [chartType, setChartType] = useState<ChartType>("candles"); const [indicators, setIndicators] = useState<Indicator[]>(["ema20"]); const [oscillators, setOscillators] = useState<Oscillator[]>([]); const [overlays, setOverlays] = useState<Overlay[]>([]); const [volume, setVolume] = useState(true); const [tool, setTool] = useState<DrawingTool>("cursor"); const [drawings, setDrawings] = useState<Drawing[]>([]); const [draft, setDraft] = useState<Point | null>(null); const [leftScale, setLeftScale] = useState(false); const [scaleMode, setScaleMode] = useState<"normal" | "log" | "percent" | "indexed">("normal"); const [menu, setMenu] = useState<"indicators" | "drawings" | "settings" | null>(null); const [full, setFull] = useState(false); const [cursor, setCursor] = useState<{ time?: string; price?: number }>({}); const [viewTick, setViewTick] = useState(0);
  const candles = useMemo(() => aggregate(observations, timeframe), [observations, timeframe]); const latest = candles.at(-1); const previous = candles.at(-2); const change = latest && previous ? latest.close - previous.close : 0; const pct = previous?.close ? (change / previous.close) * 100 : 0; const fvg = useMemo(() => zones(candles, "fvg"), [candles]); const ob = useMemo(() => zones(candles, "ob"), [candles]); const structure = useMemo(() => pivots(candles), [candles]);

  useEffect(() => { const host = hostRef.current; if (!host) return; const chart = createChart(host, chartOptions); chartRef.current = chart; const cross = (param: { time?: unknown; point?: { x: number; y: number } }) => { if (!param.point || !mainRef.current) return; const price = mainRef.current.coordinateToPrice(param.point.y); setCursor({ time: param.time ? new Date(Number(param.time) * 1000).toISOString().slice(0, 16).replace("T", " ") : undefined, price: price ?? undefined }); }; const rerender = () => setViewTick((x) => x + 1); chart.subscribeCrosshairMove(cross); chart.timeScale().subscribeVisibleLogicalRangeChange(rerender); return () => { chart.unsubscribeCrosshairMove(cross); chart.timeScale().unsubscribeVisibleLogicalRangeChange(rerender); chart.remove(); chartRef.current = null; }; }, []);

  useEffect(() => {
    const chart = chartRef.current; if (!chart || candles.length === 0) return; const existing = chart.panes().flatMap((p) => p.getSeries()); for (const s of existing) chart.removeSeries(s);
    const add = <T extends SeriesType>(s: ISeriesApi<T>) => s as ISeriesApi<SeriesType>; const priceScale = leftScale ? "left" : "right"; let main: ISeriesApi<SeriesType>;
    if (chartType === "candles") main = add(chart.addSeries(CandlestickSeries, { priceScaleId: priceScale, upColor: "#2ecf9b", downColor: "#ee6b68", borderUpColor: "#2ecf9b", borderDownColor: "#ee6b68", wickUpColor: "#2ecf9b", wickDownColor: "#ee6b68", lastValueVisible: true }));
    else if (chartType === "bars") main = add(chart.addSeries(BarSeries, { priceScaleId: priceScale, upColor: "#2ecf9b", downColor: "#ee6b68" }));
    else if (chartType === "area") main = add(chart.addSeries(AreaSeries, { priceScaleId: priceScale, lineColor: "#7db7ff", lineWidth: 2, topColor: "rgba(125,183,255,0.24)", bottomColor: "rgba(125,183,255,0.01)" }));
    else if (chartType === "baseline") main = add(chart.addSeries(BaselineSeries, { priceScaleId: priceScale, baseValue: { type: "price", price: candles[0].close }, topLineColor: "#2ecf9b", topFillColor1: "rgba(46,207,155,0.20)", topFillColor2: "rgba(46,207,155,0.03)", bottomLineColor: "#ee6b68", bottomFillColor1: "rgba(238,107,104,0.03)", bottomFillColor2: "rgba(238,107,104,0.20)" }));
    else main = add(chart.addSeries(LineSeries, { priceScaleId: priceScale, color: "#7db7ff", lineWidth: 2 }));
    main.setData(chartType === "candles" || chartType === "bars" ? candles : candles.map((x) => ({ time: x.time, value: x.close }))); mainRef.current = main;
    chart.priceScale(priceScale).applyOptions({ autoScale: true, mode: scaleMode === "normal" ? 0 : scaleMode === "log" ? 1 : scaleMode === "percent" ? 2 : 3 });
    const line = (data: { time: UTCTimestamp; value: number }[], color: string, title: string) => { const s = add(chart.addSeries(LineSeries, { priceScaleId: priceScale, color, lineWidth: 1, title })); s.setData(data); };
    if (indicators.includes("sma20")) line(sma(candles, 20), "#d6a85f", "SMA 20"); if (indicators.includes("ema20")) line(ema(candles, 20), "#77c8ff", "EMA 20"); if (indicators.includes("ema50")) line(ema(candles, 50), "#c98cff", "EMA 50"); if (indicators.includes("wma20")) line(wma(candles, 20), "#f3d36b", "WMA 20"); if (indicators.includes("vwap")) line(vwap(candles), "#ff9f68", "VWAP");
    if (indicators.includes("bb20")) { const b = bb(candles); line(b.map((x) => ({ time: x.time, value: x.upper })), "#8899aa", "BB Upper"); line(b.map((x) => ({ time: x.time, value: x.middle })), "#687789", "BB Mid"); line(b.map((x) => ({ time: x.time, value: x.lower })), "#8899aa", "BB Lower"); }
    if (volume) { const s = chart.addSeries(HistogramSeries, { priceScaleId: "", priceFormat: { type: "volume" }, color: "rgba(125,183,255,0.35)" }); s.priceScale().applyOptions({ scaleMargins: { top: 0.78, bottom: 0 } }); s.setData(candles.map((x) => ({ time: x.time, value: x.volume, color: x.close >= x.open ? "rgba(46,207,155,0.38)" : "rgba(238,107,104,0.38)" })));
    }
    let pane = 1; const paneLine = (data: { time: UTCTimestamp; value: number }[], title: string, color: string) => { const s = add(chart.addSeries(LineSeries, { color, lineWidth: 1, title }, pane)); s.setData(data); chart.panes()[pane]?.setHeight(130); pane += 1; };
    if (oscillators.includes("rsi14")) paneLine(rsi(candles), "RSI 14", "#c98cff"); if (oscillators.includes("stoch14")) paneLine(stochastic(candles), "Stoch 14", "#77c8ff"); if (oscillators.includes("atr14")) paneLine(atr(candles), "ATR 14", "#ffb86b"); if (oscillators.includes("cci20")) paneLine(cci(candles), "CCI 20", "#d6a85f"); if (oscillators.includes("adx14")) paneLine(adx(candles), "ADX 14", "#9dd68c"); if (oscillators.includes("obv")) paneLine(obv(candles), "OBV", "#77c8ff");
    if (oscillators.includes("macd")) { const m = macd(candles); const s1 = add(chart.addSeries(LineSeries, { color: "#77c8ff", lineWidth: 1, title: "MACD" }, pane)); s1.setData(m.line); const s2 = add(chart.addSeries(LineSeries, { color: "#ff9f68", lineWidth: 1, title: "Signal" }, pane)); s2.setData(m.signal); const h = add(chart.addSeries(HistogramSeries, { color: "rgba(125,183,255,0.45)", priceFormat: { type: "price" } }, pane)); h.setData(m.hist); chart.panes()[pane]?.setHeight(150); pane += 1; }
    chart.timeScale().fitContent();
  }, [candles, chartType, indicators, oscillators, volume, leftScale, scaleMode]);

  const pointFromEvent = (e: React.PointerEvent<HTMLDivElement>): Point | null => { const chart = chartRef.current; const main = mainRef.current; const host = overlayRef.current; if (!chart || !main || !host) return null; const r = host.getBoundingClientRect(); const time = chart.timeScale().coordinateToTime(e.clientX - r.left); const price = main.coordinateToPrice(e.clientY - r.top); return time === null || price === null ? null : { time: time as UTCTimestamp, price }; };
  const commitDrawing = (p: Point) => { if (!draft || tool === "cursor") return; setDrawings((d) => [...d, { tool: tool as Exclude<DrawingTool, "cursor">, a: draft, b: p }]); setDraft(null); };
  const toggle = <T extends string>(value: T, values: T[], setter: (v: T[]) => void) => setter(values.includes(value) ? values.filter((x) => x !== value) : [...values, value]);
  const screenshot = () => { const chart = chartRef.current; if (!chart) return; const canvas = chart.takeScreenshot(true, false); const a = document.createElement("a"); a.href = canvas.toDataURL("image/png"); a.download = `cfip-${symbol.replace("/", "-")}-${timeframe}.png`; a.click(); };
  const reset = () => { chartRef.current?.timeScale().fitContent(); setDrawings([]); setTool("cursor"); };

  return <div className={full ? "fixed inset-0 z-50 flex flex-col bg-[#080b10]" : "relative flex h-full min-h-0 flex-col bg-[#080b10]"}>
    <div className="flex h-10 shrink-0 items-center gap-1 border-b border-[#202a36] bg-[#0c1118] px-2 text-[11px] text-[#c5ced9]">
      <div className="mr-2 flex items-center gap-2 border-r border-[#202a36] pr-3"><strong className="text-white">{symbol}</strong><span className={pct >= 0 ? "text-emerald-400" : "text-red-400"}>{latest?.close.toFixed(5) ?? "—"}</span><span className={pct >= 0 ? "text-emerald-400" : "text-red-400"}>{pct >= 0 ? "+" : ""}{pct.toFixed(2)}%</span></div>
      {TIMEFRAMES.map((tf) => <button key={tf} onClick={() => setTimeframe(tf)} className={`px-2 py-1 ${tf === timeframe ? "bg-[#263447] text-white" : "text-[#8794a5] hover:text-white"}`}>{tf}</button>)}
      <div className="ml-auto flex items-center gap-1"><button onClick={() => setMenu(menu === "indicators" ? null : "indicators")} className="rounded px-2 py-1 hover:bg-[#1a2330]">Indicators</button><button onClick={() => setMenu(menu === "drawings" ? null : "drawings")} className="rounded px-2 py-1 hover:bg-[#1a2330]">Draw</button><button onClick={() => setMenu(menu === "settings" ? null : "settings")} className="rounded px-2 py-1 hover:bg-[#1a2330]">Settings</button><button onClick={screenshot} className="px-2 py-1 hover:bg-[#1a2330]">Export</button><button onClick={() => setFull(!full)} className="px-2 py-1 hover:bg-[#1a2330]">{full ? "Exit" : "Fullscreen"}</button></div>
    </div>
    <div className="flex min-h-0 flex-1">
      <aside className="flex w-11 shrink-0 flex-col items-center gap-1 border-r border-[#202a36] bg-[#0b1017] py-2">{(["cursor", "horizontal", "vertical", "trendline", "ray", "rectangle", "fib"] as DrawingTool[]).map((x) => <button key={x} onClick={() => setTool(x)} title={x} className={`h-8 w-9 text-[10px] ${tool === x ? "bg-[#263447] text-white" : "text-[#7d8b9d] hover:bg-[#18212d]"}`}>{x === "cursor" ? "✥" : x === "horizontal" ? "—" : x === "vertical" ? "│" : x === "trendline" ? "╱" : x === "ray" ? "↗" : x === "rectangle" ? "□" : "Fib"}</button>)}<div className="my-1 h-px w-7 bg-[#202a36]" /><button onClick={reset} title="Reset" className="h-8 w-9 text-[10px] text-[#7d8b9d] hover:bg-[#18212d]">↺</button><button onClick={() => setDrawings([])} title="Delete drawings" className="h-8 w-9 text-[10px] text-[#7d8b9d] hover:bg-[#18212d]">⌫</button></aside>
      <div className="relative min-h-0 min-w-0 flex-1"><div ref={hostRef} className="absolute inset-0" /><div ref={overlayRef} className="absolute inset-0" onPointerDown={(e) => { const p = pointFromEvent(e); if (!p || tool === "cursor") return; setDraft(p); }} onPointerUp={(e) => { const p = pointFromEvent(e); if (p) commitDrawing(p); }}>
        <svg key={viewTick} className="pointer-events-none absolute inset-0 h-full w-full overflow-visible">{drawings.map((d, i) => { const chart = chartRef.current; const main = mainRef.current; if (!chart || !main) return null; const x1 = chart.timeScale().timeToCoordinate(d.a.time); const x2 = chart.timeScale().timeToCoordinate(d.b.time); const y1 = main.priceToCoordinate(d.a.price); const y2 = main.priceToCoordinate(d.b.price); if (x1 === null || x2 === null || y1 === null || y2 === null) return null; if (d.tool === "horizontal") return <line key={i} x1={0} x2="100%" y1={y1} y2={y1} stroke="#d6a85f" strokeDasharray="5 4" />; if (d.tool === "vertical") return <line key={i} x1={x1} x2={x1} y1={0} y2="100%" stroke="#d6a85f" strokeDasharray="5 4" />; if (d.tool === "rectangle") return <rect key={i} x={Math.min(x1,x2)} y={Math.min(y1,y2)} width={Math.abs(x2-x1)} height={Math.abs(y2-y1)} fill="rgba(125,183,255,0.08)" stroke="#7db7ff" />; if (d.tool === "fib") { const dy = y2-y1; return <g key={i}>{[0,0.236,0.382,0.5,0.618,0.786,1].map((f) => <line key={f} x1={Math.min(x1,x2)} x2={Math.max(x1,x2)} y1={y1+dy*f} y2={y1+dy*f} stroke="#8794a5" strokeDasharray="4 3" />)}</g>; } return <line key={i} x1={x1} y1={y1} x2={d.tool === "ray" ? "100%" : x2} y2={d.tool === "ray" ? y1 + (y2-y1) * ((overlayRef.current?.clientWidth ?? 1)-x1)/Math.max(1,x2-x1) : y2} stroke="#7db7ff" strokeWidth="1.5" />; })}</svg>
        {draft && <div className="pointer-events-none absolute left-2 top-8 rounded border border-[#7db7ff] bg-[#0c1118] px-1 text-[9px] text-[#b9c7d8]">Drawing: {tool}</div>}
      </div><div className="pointer-events-none absolute left-3 top-2 flex items-center gap-3 text-[10px] text-[#8b98a9]"><span>O {latest?.open.toFixed(5) ?? "—"}</span><span>H {latest?.high.toFixed(5) ?? "—"}</span><span>L {latest?.low.toFixed(5) ?? "—"}</span><span>C {latest?.close.toFixed(5) ?? "—"}</span>{cursor.price !== undefined && <span>Crosshair {cursor.price.toFixed(5)}</span>}</div>
      </div>
    </div>
    <div className="flex h-7 shrink-0 items-center justify-between border-t border-[#202a36] bg-[#0c1118] px-3 text-[9px] text-[#728093]"><span>{candles.length} bars · {timeframe} · {tool}</span><span>TradingView Lightweight Charts™ · CFIP normalized market data</span></div>
    {menu && <div className="absolute right-2 top-11 z-30 w-80 border border-[#2a3746] bg-[#101722]/95 p-3 text-[11px] shadow-2xl backdrop-blur">
      {menu === "indicators" && <><div className="mb-2 font-semibold text-white">Indicators & studies</div><div className="grid grid-cols-2 gap-1">{INDICATORS.map((x) => <button key={x.id} onClick={() => toggle(x.id, indicators, setIndicators)} className={`rounded px-2 py-1 text-left ${indicators.includes(x.id) ? "bg-[#2b394c] text-white" : "bg-[#171f2a] text-[#8794a5]"}`}>{x.label}</button>)}{OSCILLATORS.map((x) => <button key={x.id} onClick={() => toggle(x.id, oscillators, setOscillators)} className={`rounded px-2 py-1 text-left ${oscillators.includes(x.id) ? "bg-[#2b394c] text-white" : "bg-[#171f2a] text-[#8794a5]"}`}>{x.label}</button>)}</div></>}
      {menu === "drawings" && <><div className="mb-2 font-semibold text-white">Analysis overlays</div><div className="grid grid-cols-2 gap-1">{(["fvg", "ob", "structure", "liquidity", "sessions"] as Overlay[]).map((x) => <button key={x} onClick={() => toggle(x, overlays, setOverlays)} className={`rounded px-2 py-1 capitalize ${overlays.includes(x) ? "bg-[#2b394c] text-white" : "bg-[#171f2a] text-[#8794a5]"}`}>{x}</button>)}</div><div className="mt-3 border-t border-[#263241] pt-2 text-[#7d8b9d]">Drawing tools are active in the left rail. Click-drag between chart coordinates.</div></>}
      {menu === "settings" && <><div className="mb-2 font-semibold text-white">Chart settings</div><div className="space-y-2"><label className="flex items-center justify-between">Chart type<select value={chartType} onChange={(e) => setChartType(e.target.value as ChartType)} className="bg-[#171f2a] px-2 py-1">{["candles","bars","line","area","baseline"].map((x) => <option key={x}>{x}</option>)}</select></label><label className="flex items-center justify-between">Price scale<select value={scaleMode} onChange={(e) => setScaleMode(e.target.value as typeof scaleMode)} className="bg-[#171f2a] px-2 py-1"><option value="normal">Normal</option><option value="log">Log</option><option value="percent">%</option><option value="indexed">Indexed 100</option></select></label><label className="flex items-center justify-between">Left scale<input type="checkbox" checked={leftScale} onChange={(e) => setLeftScale(e.target.checked)} /></label><label className="flex items-center justify-between">Volume<input type="checkbox" checked={volume} onChange={(e) => setVolume(e.target.checked)} /></label><button onClick={reset} className="w-full bg-[#1b2735] py-1 text-white">Fit / reset view</button></div></>}
    </div>}
  </div>;
}
